# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ShoppingCartTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShoppingCartTest

    # Easily register and dequeue cells without using strings
    # https://fmo91.github.io/DequeuableRegistrable/
     pod 'DequeuableRegistrable', :git => 'https://github.com/fmo91/DequeuableRegistrable/'

  target 'ShoppingCartTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

end
